# Deploy the pods
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: exporter-deployment
spec:
  selector:
    matchLabels:
      app: exporter
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: exporter
    spec:
      containers:
      - name: exporter
        image: 941681414890.dkr.ecr.us-east-1.amazonaws.com/swaggertest:v1
        ports:
        - containerPort: 3030
---
# This service is used to expose the pods on a port
apiVersion: v1
kind: Service
metadata:
  name: exporter-service
spec:
  selector:
    app: exporter
  ports:
    - port: 3030
      protocol: TCP
